# Generated by Django 5.2.1 on 2025-07-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='front_image',
            field=models.FileField(upload_to='footwear'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='side_image',
            field=models.FileField(upload_to='footwear'),
        ),
    ]
