# Generated by Django 5.2.1 on 2025-07-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliza', '0002_alter_footwear_front_image_alter_footwear_side_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='front_image',
            field=models.ImageField(upload_to='footwear/'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='side_image',
            field=models.ImageField(upload_to='footwear/'),
        ),
    ]
